/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modele.Contrat;
import modele.Responsable;
import modele.RegistreApp;
import modele.RegistreClient;
import persistance.ManipulationFichier;
import utils.Utilitaire;

/**
 *
 * @author MarcAntoine
 */
public class FenContrat extends javax.swing.JFrame {

    /**
     * Creates new form FenContrat
     */
    public FenContrat() {
        initComponents();
        ManipulationFichier.lireFichierProprio("Proprietaires.txt", tblProprio);
        ObjProprio = new String[tblProprio.getColumnCount()];
        for (int i = 0; i < tblProprio.getColumnCount(); i++) {
            ObjProprio[i] = String.valueOf(tblProprio.getValueAt(0, i));
        }
        jScrollPaneProprio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabGlobal = new javax.swing.JTabbedPane();
        panelClient = new javax.swing.JPanel();
        panelClientSearch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnUpdateRow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListe = new javax.swing.JTable();
        panelApp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListeApp = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblImageApp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelContrat = new javax.swing.JPanel();
        jPanelGlobal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        lblImagesBail = new javax.swing.JLabel();
        jPanelBailleur = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNomBail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNoBail = new javax.swing.JTextField();
        txtRueBail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelBail = new javax.swing.JTextField();
        jPanelLocataire = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNomLoc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNoLoc = new javax.swing.JTextField();
        txtRueLoc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelLoc = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPNomLoc = new javax.swing.JTextField();
        jPanelDescription = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtTypeApp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEtageApp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtNoApp = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtRueApp = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtNunAApp = new javax.swing.JTextField();
        txtMeuble = new javax.swing.JComboBox<>();
        txtChauffage = new javax.swing.JComboBox<>();
        txtParking = new javax.swing.JComboBox<>();
        jPanelPrix = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtDuree = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtDateDebut = new com.toedter.calendar.JDateChooser();
        txtDateFin = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtMontant = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCout = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtMontantTotal = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnValider = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        jScrollPaneProprio = new javax.swing.JScrollPane();
        tblProprio = new javax.swing.JTable();
        txtMontantFreq = new javax.swing.JComboBox<>();
        txtCoutFreq = new javax.swing.JComboBox<>();
        txtMontantTotalFreq = new javax.swing.JComboBox<>();
        txtDatePremierTerme = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Création d'un contrat");

        jTabGlobal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.gray));
        jTabGlobal.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabGlobal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabGlobalStateChanged(evt);
            }
        });

        panelClientSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel1.setText("Nom:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setText("Prénom:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtNom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtPrenom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View.png"))); // NOI18N
        btn_search.setText("Recherche");
        btn_search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eye.png"))); // NOI18N
        jLabel4.setText("Choix du locataire!");

        btnUpdateRow.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUpdateRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientSearchLayout = new javax.swing.GroupLayout(panelClientSearch);
        panelClientSearch.setLayout(panelClientSearchLayout);
        panelClientSearchLayout.setHorizontalGroup(
            panelClientSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientSearchLayout.createSequentialGroup()
                .addGroup(panelClientSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientSearchLayout.createSequentialGroup()
                        .addGroup(panelClientSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelClientSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNom)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnUpdateRow))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1308, Short.MAX_VALUE))
        );
        panelClientSearchLayout.setVerticalGroup(
            panelClientSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientSearchLayout.createSequentialGroup()
                .addGroup(panelClientSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelClientSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateRow, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelClientSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_search)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        tblListe.setAutoCreateRowSorter(true);
        tblListe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Date de naissance", "No téléphone", "No identification", "No", "Rue", "Province", "Ville", "Code", "Choix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListe.getTableHeader().setReorderingAllowed(false);
        tblListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblListeMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblListe);

        javax.swing.GroupLayout panelClientLayout = new javax.swing.GroupLayout(panelClient);
        panelClient.setLayout(panelClientLayout);
        panelClientLayout.setHorizontalGroup(
            panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelClientSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1755, Short.MAX_VALUE)
        );
        panelClientLayout.setVerticalGroup(
            panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientLayout.createSequentialGroup()
                .addComponent(panelClientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
        );

        jTabGlobal.addTab("Locataire", new javax.swing.ImageIcon(getClass().getResource("/images/People.png")), panelClient); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblListeApp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "App", "NoCivique", "Addresse", "Province", "Ville", "Code Postal", "Type", "Etage", "Disponible", "En réparation", "Choix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListeAppMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListeApp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1468, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImageApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImageApp, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImageApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eye.png"))); // NOI18N
        jLabel3.setText("Choix de l'appartement!");

        javax.swing.GroupLayout panelAppLayout = new javax.swing.GroupLayout(panelApp);
        panelApp.setLayout(panelAppLayout);
        panelAppLayout.setHorizontalGroup(
            panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAppLayout.createSequentialGroup()
                .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAppLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAppLayout.setVerticalGroup(
            panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAppLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabGlobal.addTab("Appartement", new javax.swing.ImageIcon(getClass().getResource("/images/Home.png")), panelApp); // NOI18N

        panelContrat.setBackground(new java.awt.Color(255, 255, 255));
        panelContrat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanelGlobal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGlobal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImagesBail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enteteBail2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagesBail)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(lblImagesBail)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelBailleur.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Nom");

        txtNomBail.setEditable(false);
        txtNomBail.setBackground(new java.awt.Color(255, 255, 255));
        txtNomBail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNomBail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomBailActionPerformed(evt);
            }
        });

        jLabel6.setText("No");

        jLabel7.setText("Adresse");

        txtNoBail.setEditable(false);
        txtNoBail.setBackground(new java.awt.Color(255, 255, 255));
        txtNoBail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtRueBail.setEditable(false);
        txtRueBail.setBackground(new java.awt.Color(255, 255, 255));
        txtRueBail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setText("No de téléphone");

        txtTelBail.setEditable(false);
        txtTelBail.setBackground(new java.awt.Color(255, 255, 255));
        txtTelBail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanelBailleurLayout = new javax.swing.GroupLayout(jPanelBailleur);
        jPanelBailleur.setLayout(jPanelBailleurLayout);
        jPanelBailleurLayout.setHorizontalGroup(
            jPanelBailleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBailleurLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBailleurLayout.createSequentialGroup()
                .addGroup(jPanelBailleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBailleurLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBailleurLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelBail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(104, 104, 104))
            .addGroup(jPanelBailleurLayout.createSequentialGroup()
                .addComponent(txtNomBail)
                .addContainerGap())
            .addGroup(jPanelBailleurLayout.createSequentialGroup()
                .addComponent(txtNoBail, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRueBail)
                .addContainerGap())
        );
        jPanelBailleurLayout.setVerticalGroup(
            jPanelBailleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBailleurLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomBail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBailleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBailleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoBail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRueBail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBailleurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTelBail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanelLocataire.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Nom");

        txtNomLoc.setEditable(false);
        txtNomLoc.setBackground(new java.awt.Color(255, 255, 255));
        txtNomLoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel11.setText("No");

        jLabel12.setText("Adresse");

        txtNoLoc.setEditable(false);
        txtNoLoc.setBackground(new java.awt.Color(255, 255, 255));
        txtNoLoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtRueLoc.setEditable(false);
        txtRueLoc.setBackground(new java.awt.Color(255, 255, 255));
        txtRueLoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRueLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRueLocActionPerformed(evt);
            }
        });

        jLabel14.setText("No de téléphone");

        txtTelLoc.setEditable(false);
        txtTelLoc.setBackground(new java.awt.Color(255, 255, 255));
        txtTelLoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel33.setText("Prénom");

        txtPNomLoc.setEditable(false);
        txtPNomLoc.setBackground(new java.awt.Color(255, 255, 255));
        txtPNomLoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanelLocataireLayout = new javax.swing.GroupLayout(jPanelLocataire);
        jPanelLocataire.setLayout(jPanelLocataireLayout);
        jPanelLocataireLayout.setHorizontalGroup(
            jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocataireLayout.createSequentialGroup()
                .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocataireLayout.createSequentialGroup()
                        .addComponent(txtNoLoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRueLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLocataireLayout.createSequentialGroup()
                        .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLocataireLayout.createSequentialGroup()
                                .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLocataireLayout.createSequentialGroup()
                                .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelLocataireLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(105, 105, 105))
                                    .addGroup(jPanelLocataireLayout.createSequentialGroup()
                                        .addComponent(txtNomLoc)
                                        .addGap(9, 9, 9)))
                                .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(txtPNomLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLocataireLayout.setVerticalGroup(
            jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocataireLayout.createSequentialGroup()
                .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLocataireLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLocataireLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPNomLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLocataireLayout.createSequentialGroup()
                        .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRueLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocataireLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanelLocataireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addContainerGap())))
        );

        jPanelDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setText("Type appartement");

        txtTypeApp.setEditable(false);
        txtTypeApp.setBackground(new java.awt.Color(255, 255, 255));
        txtTypeApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel16.setText("No étage");

        txtEtageApp.setEditable(false);
        txtEtageApp.setBackground(new java.awt.Color(255, 255, 255));
        txtEtageApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel17.setText("Des meubles sont loués et inclus dans le loyer.");

        jLabel18.setText("Le chauffage est inclus dans le loyer.");

        jLabel19.setText("Le stationnement est inclus dans le loyer.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("DESCRIPTION ET DESTINATION DU LOGEMENT LOUÉ, DES ACCESSOIRES ET DÉPENDANCES");
        jLabel8.setToolTipText("");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel28.setText("No");

        txtNoApp.setEditable(false);
        txtNoApp.setBackground(new java.awt.Color(255, 255, 255));
        txtNoApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel29.setText("Rue");

        txtRueApp.setEditable(false);
        txtRueApp.setBackground(new java.awt.Color(255, 255, 255));
        txtRueApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel30.setText("App");

        txtNunAApp.setEditable(false);
        txtNunAApp.setBackground(new java.awt.Color(255, 255, 255));
        txtNunAApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtMeuble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUI", "NON" }));
        txtMeuble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMeubleActionPerformed(evt);
            }
        });

        txtChauffage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUI", "NON" }));

        txtParking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUI", "NON" }));

        javax.swing.GroupLayout jPanelDescriptionLayout = new javax.swing.GroupLayout(jPanelDescription);
        jPanelDescription.setLayout(jPanelDescriptionLayout);
        jPanelDescriptionLayout.setHorizontalGroup(
            jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDescriptionLayout.createSequentialGroup()
                .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelDescriptionLayout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(77, 77, 77))
                        .addComponent(txtTypeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDescriptionLayout.createSequentialGroup()
                        .addComponent(txtEtageApp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(484, 484, 484))
                    .addGroup(jPanelDescriptionLayout.createSequentialGroup()
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDescriptionLayout.createSequentialGroup()
                                .addComponent(txtRueApp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNunAApp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMeuble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChauffage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(191, 191, 191))))
        );
        jPanelDescriptionLayout.setVerticalGroup(
            jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescriptionLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDescriptionLayout.createSequentialGroup()
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel28)
                                .addComponent(jLabel29))
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRueApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNunAApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(jPanelDescriptionLayout.createSequentialGroup()
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMeuble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtChauffage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTypeApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtageApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPrix.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setText("Ce bail a une durée de");

        jLabel21.setText("Date de début");

        jLabel22.setText("Date de fin");

        txtDuree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("(mois)");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 51, 102));
        jLabel31.setText("DURÉE DU BAIL");
        jLabel31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelPrixLayout = new javax.swing.GroupLayout(jPanelPrix);
        jPanelPrix.setLayout(jPanelPrixLayout);
        jPanelPrixLayout.setHorizontalGroup(
            jPanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrixLayout.createSequentialGroup()
                .addGroup(jPanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrixLayout.createSequentialGroup()
                        .addComponent(txtDuree, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPrixLayout.setVerticalGroup(
            jPanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrixLayout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addComponent(txtDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setText("Montant du loyer");

        txtMontant.setText("0");
        txtMontant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtMontant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontantFocusLost(evt);
            }
        });
        txtMontant.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMontantInputMethodTextChanged(evt);
            }
        });
        txtMontant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontantActionPerformed(evt);
            }
        });

        jLabel24.setText("Cout total des services");

        txtCout.setText("0");
        txtCout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCoutFocusLost(evt);
            }
        });

        jLabel25.setText("Montant total du loyer");

        txtMontantTotal.setEditable(false);
        txtMontantTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtMontantTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtMontantTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontantTotalActionPerformed(evt);
            }
        });

        jLabel26.setText("Date du premier terme");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 51, 102));
        jLabel32.setText("LOYER");
        jLabel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane1.setText("Loyer: Le loyer est payable par versements égaux  ne dépassant pas un mois, sauf le dernier versement, qui peut être moins élevé.\n\nPaiement des autres termes: Le loyer est payable le premier jour de chaque terme.");
        jScrollPane3.setViewportView(jTextPane1);

        btnValider.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yes.png"))); // NOI18N
        btnValider.setText("Valider");
        btnValider.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        btnQuitter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        jScrollPaneProprio.setForeground(new java.awt.Color(240, 240, 240));

        tblProprio.setForeground(new java.awt.Color(240, 240, 240));
        tblProprio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Tel", "No", "Rue", "Province", "Ville", "Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneProprio.setViewportView(tblProprio);

        txtMontantFreq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Par mois", "Par semaine" }));

        txtCoutFreq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Par mois", "Par semaine" }));

        txtMontantTotalFreq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Par mois", "Par semaine" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneProprio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtMontant, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMontantFreq, 0, 105, Short.MAX_VALUE)
                            .addComponent(txtCoutFreq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(85, 85, 85)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(txtMontantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontantTotalFreq, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26)
                    .addComponent(txtDatePremierTerme, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantTotalFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatePremierTerme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCoutFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnValider)
                        .addComponent(btnQuitter))
                    .addComponent(jScrollPaneProprio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("ENTRE LE LOCATEUR                                                                         ET LE LOCATAIRE");
        jLabel13.setToolTipText("");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPrix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanelBailleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLocataire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLocataire, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBailleur, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGlobalLayout = new javax.swing.GroupLayout(jPanelGlobal);
        jPanelGlobal.setLayout(jPanelGlobalLayout);
        jPanelGlobalLayout.setHorizontalGroup(
            jPanelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGlobalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGlobalLayout.setVerticalGroup(
            jPanelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelContratLayout = new javax.swing.GroupLayout(panelContrat);
        panelContrat.setLayout(panelContratLayout);
        panelContratLayout.setHorizontalGroup(
            panelContratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContratLayout.createSequentialGroup()
                .addComponent(jPanelGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        panelContratLayout.setVerticalGroup(
            panelContratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabGlobal.addTab("Contrat", new javax.swing.ImageIcon(getClass().getResource("/images/Good mark.png")), panelContrat); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabGlobal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        isClientSelect = false;
        String nomClient = txtNom.getText();
        String prenomClient = txtPrenom.getText();
        regClient = new RegistreClient();
        boolean resultat = ManipulationFichier.rechercherInfosToFile("Clients.txt", nomClient, prenomClient, regClient, tblListe);
    }//GEN-LAST:event_btn_searchActionPerformed

    private void tblListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListeMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblListe.getModel();
        int count = tblListe.getRowCount();
        rowIndexClient = tblListe.getSelectedRow();
        for (int i = 0; i < count; i++) {
            if (i != rowIndexClient) {
                tblListe.setValueAt(false, i, 10);
            }
            if ((Boolean) model.getValueAt(rowIndexClient, 10)) {
                isClientSelect = true;
            }
        }
    }//GEN-LAST:event_tblListeMouseClicked

    private void tblListeAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListeAppMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblListeApp.getModel();
        int count = tblListeApp.getRowCount();
        rowIndexApp = tblListeApp.getSelectedRow();
        for (int i = 0; i < count; i++) {
            if (i != rowIndexApp) {
                tblListeApp.setValueAt(false, i, 10);
            }
            if ((Boolean) model.getValueAt(rowIndexApp, 10)) {
                isAppSelect = true;
            }
        }
        loaderImages(rowIndexApp, lblImageApp);
    }//GEN-LAST:event_tblListeAppMouseClicked

    private void jTabGlobalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabGlobalStateChanged
        //Initialisation
        if (jTabGlobal.getSelectedIndex() == 0) {
            isClientSelect = false;
            isAppSelect = false;
        }

        if (jTabGlobal.getSelectedIndex() == 1) {
            //Liste des appartements
            regApp = new RegistreApp();
            ManipulationFichier.lireFichierApp("Appartements.txt", regApp, tblListeApp);
        }
        //Contrat si Client et Appartement selectionnés
        if (jTabGlobal.getSelectedIndex() == 2 && isClientSelect == true && isAppSelect == true) {
            Utilitaire.copierDonneesToContrat(ObjProprio, regClient, rowIndexClient, regApp, rowIndexApp, txtNomBail, txtNoBail, txtRueBail, txtTelBail,
                    txtNomLoc, txtPNomLoc, txtNoLoc, txtRueLoc, txtTelLoc,
                    txtNoApp, txtRueApp, txtNunAApp, txtTypeApp, txtEtageApp);
        }
    }//GEN-LAST:event_jTabGlobalStateChanged

    private void txtRueLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRueLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRueLocActionPerformed

    private void txtNomBailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomBailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomBailActionPerformed

    private void btnUpdateRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRowActionPerformed
        int i = tblListe.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblListe.getModel();
        if (i >= 0) {
            model.setValueAt(true, i, 10);
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnUpdateRowActionPerformed

    private void tblListeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListeMousePressed

    }//GEN-LAST:event_tblListeMousePressed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        try {
            //Retourner la ligne 
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String NomBail = txtNomBail.getText();
            String NoBail = txtNoBail.getText();
            String RueBail = txtRueBail.getText();
            String TelBail = txtTelBail.getText();
            String NomLoc = txtNomLoc.getText();
            String PrenomLoc = txtPNomLoc.getText();
            String NoLoc = txtNoLoc.getText();
            String RueLoc = txtRueLoc.getText();
            String TelLoc = txtTelLoc.getText();
            String NoApp = txtNoApp.getText();
            String RueApp = txtRueApp.getText();
            String NunAApp = txtNunAApp.getText();
            String TypeApp = txtTypeApp.getText();
            int EtageApp = Integer.parseInt(txtEtageApp.getText());
            String Meuble = (String) txtMeuble.getSelectedItem();
            String Chauffage = (String) txtChauffage.getSelectedItem();
            String Parking = (String) txtParking.getSelectedItem();
            int Duree = Integer.parseInt(txtDuree.getText());
            String Debut = DateFormat.getDateInstance().format(txtDateDebut.getDate());

            String Fin = DateFormat.getDateInstance().format(txtDateFin.getDate());
            double Montant = Double.parseDouble(txtMontant.getText());
            String MontantFreq = (String) txtMontantFreq.getSelectedItem();
            double Cout = Double.parseDouble(txtCout.getText());
            String CoutFreq = (String) txtCoutFreq.getSelectedItem();
            double MontantTotal = Double.parseDouble(txtMontantTotal.getText());
            String MontantTotalFreq = (String) txtMontantTotalFreq.getSelectedItem();
            String PremierTerme = DateFormat.getDateInstance().format(txtDatePremierTerme.getDate());
            Contrat contrat = new Contrat(NomBail, NoBail, RueBail, TelBail, NomLoc, PrenomLoc, NoLoc, RueLoc, TelLoc,
                    NoApp, RueApp, NunAApp, TypeApp, EtageApp, Meuble, Chauffage,
                    Parking, Duree, Debut, Fin, Montant, MontantFreq, Cout, CoutFreq, MontantTotal, MontantTotalFreq, PremierTerme);
            String ligne = Utilitaire.retournerLigneFichier(contrat);
            ManipulationFichier.ecrireFichier("Contrats.txt", ligne);
            //Mettre a jour la disponibilite de l'appartement a partir de l'indexRowApp
            ManipulationFichier.ecrireFichier("Appartements.txt", regApp, rowIndexApp);
            JOptionPane.showMessageDialog(null,
                    "Opération réussie avec succès", "Informations sur le contrat",
                    JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Saisie non correcte.\nVeuillez entrer les bonnes informations", "EXCEPTION",
                    JOptionPane.ERROR_MESSAGE);
            requestFocusInWindow();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null,
                    "Saisie non correcte.\nVeuillez vérifier les informations", "EXCEPTION",
                    JOptionPane.ERROR_MESSAGE);
            requestFocusInWindow();
        }
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        dispose();
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void txtMeubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMeubleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMeubleActionPerformed

    private void txtMontantInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMontantInputMethodTextChanged
       
    }//GEN-LAST:event_txtMontantInputMethodTextChanged

    private void txtMontantTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontantTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontantTotalActionPerformed

    private void txtMontantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontantFocusLost
       txtMontantTotal.setText(calculerTotal());
    }//GEN-LAST:event_txtMontantFocusLost

    private void txtMontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontantActionPerformed

    private void txtCoutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCoutFocusLost
       txtMontantTotal.setText(calculerTotal());
    }//GEN-LAST:event_txtCoutFocusLost
    
    private String calculerTotal(){
       double val1= Double.parseDouble(txtMontant.getText());
       double val2= Double.parseDouble(txtCout.getText());
       double total= val1+val2;
       return (String.valueOf(total));
    }
    
    private boolean isClientSelect = false;
    private boolean isAppSelect = false;
    private int rowIndexClient = -1;
    private int rowIndexApp = -1;
    private RegistreClient regClient;
    private RegistreApp regApp;
    private String[] ObjProprio;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnUpdateRow;
    private javax.swing.JButton btnValider;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBailleur;
    private javax.swing.JPanel jPanelDescription;
    private javax.swing.JPanel jPanelGlobal;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLocataire;
    private javax.swing.JPanel jPanelPrix;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneProprio;
    private javax.swing.JTabbedPane jTabGlobal;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblImageApp;
    private javax.swing.JLabel lblImagesBail;
    private javax.swing.JPanel panelApp;
    private javax.swing.JPanel panelClient;
    private javax.swing.JPanel panelClientSearch;
    private javax.swing.JPanel panelContrat;
    private javax.swing.JTable tblListe;
    private javax.swing.JTable tblListeApp;
    private javax.swing.JTable tblProprio;
    private javax.swing.JComboBox<String> txtChauffage;
    private javax.swing.JTextField txtCout;
    private javax.swing.JComboBox<String> txtCoutFreq;
    private com.toedter.calendar.JDateChooser txtDateDebut;
    private com.toedter.calendar.JDateChooser txtDateFin;
    private com.toedter.calendar.JDateChooser txtDatePremierTerme;
    private javax.swing.JTextField txtDuree;
    private javax.swing.JTextField txtEtageApp;
    private javax.swing.JComboBox<String> txtMeuble;
    private javax.swing.JTextField txtMontant;
    private javax.swing.JComboBox<String> txtMontantFreq;
    private javax.swing.JTextField txtMontantTotal;
    private javax.swing.JComboBox<String> txtMontantTotalFreq;
    private javax.swing.JTextField txtNoApp;
    private javax.swing.JTextField txtNoBail;
    private javax.swing.JTextField txtNoLoc;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNomBail;
    private javax.swing.JTextField txtNomLoc;
    private javax.swing.JTextField txtNunAApp;
    private javax.swing.JTextField txtPNomLoc;
    private javax.swing.JComboBox<String> txtParking;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtRueApp;
    private javax.swing.JTextField txtRueBail;
    private javax.swing.JTextField txtRueLoc;
    private javax.swing.JTextField txtTelBail;
    private javax.swing.JTextField txtTelLoc;
    private javax.swing.JTextField txtTypeApp;
    // End of variables declaration//GEN-END:variables

    private void loaderImages(int noApp, JLabel lblImageApp) {

        if (noApp == 0) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images0.jpg")));
        }
        if (noApp == 1) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images1.jpg")));
        }
        if (noApp == 2) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images2.jpg")));
        }
        if (noApp == 3) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images3.jpg")));
        }
        if (noApp == 4) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images4.jpg")));
        }
        if (noApp == 5) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images5.jpg")));
        }
        if (noApp == 6) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images6.jpg")));
        }
        if (noApp == 7) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images7.jpg")));
        }
        if (noApp == 8) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images8.jpg")));
        }
        if (noApp == 9) {
            lblImageApp.setIcon(new ImageIcon(getClass().getResource("/images/images9.jpg")));
        }
    }
}
