/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JTextField;
import modele.Usager;
import utils.Utilitaire;

/**
 *
 * @author 1795657
 */
public class FenMenuPrincipal extends javax.swing.JFrame {

    FenMenuPrincipal(Usager usager) {
        initComponents();
        ajouterMenuAdmin();
        this.setTitle(txtTitle + "[" + usager.getPrenom() + " " + usager.getNom() + "]");
        Utilitaire.gererMenu(usager, listeMenusAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelGlobal = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFicher = new javax.swing.JMenu();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuItemUsager = new javax.swing.JMenuItem();
        jMenuItemResidence = new javax.swing.JMenuItem();
        jMenuItemApp = new javax.swing.JMenuItem();
        jMenuOperation = new javax.swing.JMenu();
        jMenuRapport = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        panelGlobal.setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout panelGlobalLayout = new javax.swing.GroupLayout(panelGlobal);
        panelGlobal.setLayout(panelGlobalLayout);
        panelGlobalLayout.setHorizontalGroup(
            panelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        panelGlobalLayout.setVerticalGroup(
            panelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jMenuFicher.setText("Fichier");
        jMenuBar.add(jMenuFicher);

        jMenuAdmin.setText("Administration");

        jMenuItemUsager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/People.png"))); // NOI18N
        jMenuItemUsager.setText("Gestion des Usagers");
        jMenuItemUsager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsagerActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemUsager);

        jMenuItemResidence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.png"))); // NOI18N
        jMenuItemResidence.setText("Gestion des résidences");
        jMenuItemResidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResidenceActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemResidence);

        jMenuItemApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.png"))); // NOI18N
        jMenuItemApp.setText("Gestion des appartements");
        jMenuItemApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAppActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemApp);

        jMenuBar.add(jMenuAdmin);

        jMenuOperation.setText("Opération");
        jMenuBar.add(jMenuOperation);

        jMenuRapport.setText("Rapport");
        jMenuBar.add(jMenuRapport);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsagerActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenUsager().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItemUsagerActionPerformed

    private void jMenuItemResidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResidenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemResidenceActionPerformed

    private void jMenuItemAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAppActionPerformed

    private void ajouterMenuAdmin() {
        listeMenusAdmin.add(jMenuItemUsager);
        listeMenusAdmin.add(jMenuItemResidence);
        listeMenusAdmin.add(jMenuItemApp);
    }

    private ArrayList<JMenuItem> listeMenusAdmin = new ArrayList<JMenuItem>();
    private final String txtTitle = "RESIDENCE DU CALME ";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFicher;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemApp;
    private javax.swing.JMenuItem jMenuItemResidence;
    private javax.swing.JMenuItem jMenuItemUsager;
    private javax.swing.JMenu jMenuOperation;
    private javax.swing.JMenu jMenuRapport;
    private javax.swing.JPanel panelGlobal;
    // End of variables declaration//GEN-END:variables
}
