/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JTextField;
import modele.Responsable;
import modele.Usager;
import vueRapports.FenClientRapport;
import utils.Utilitaire;
import vueRapports.FenAppRapport;
import vueRapports.FenPaiementRapport;

/**
 *
 * @author 1795657
 */
public class FenMenuPrincipal extends javax.swing.JFrame {

    FenMenuPrincipal(Usager usager) {
        initComponents();
        ajouterMenuAdmin();
        this.setTitle(txtTitle + "[" + usager.getPrenom() + " " + usager.getNom() + "]");
        Utilitaire.gererMenu(usager, listeMenusAdmin);
    }

    FenMenuPrincipal() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelGlobal = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFicher = new javax.swing.JMenu();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuItemProprio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemUsager = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemApp = new javax.swing.JMenuItem();
        jMenuOperation = new javax.swing.JMenu();
        jMenuItemClient = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClient1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPaie = new javax.swing.JMenuItem();
        jMenuRapport = new javax.swing.JMenu();
        jMenuRepLoc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRepApp = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRepPaie = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        panelGlobal.setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout panelGlobalLayout = new javax.swing.GroupLayout(panelGlobal);
        panelGlobal.setLayout(panelGlobalLayout);
        panelGlobalLayout.setHorizontalGroup(
            panelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        panelGlobalLayout.setVerticalGroup(
            panelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jMenuFicher.setText("Fichier");

        jMenuItemQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        jMenuItemQuitter.setText("Quitter");
        jMenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitterActionPerformed(evt);
            }
        });
        jMenuFicher.add(jMenuItemQuitter);
        jMenuFicher.add(jSeparator7);

        jMenuBar.add(jMenuFicher);

        jMenuAdmin.setText("Administration");

        jMenuItemProprio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProprio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Boss.png"))); // NOI18N
        jMenuItemProprio.setText("Ajouter le responsable");
        jMenuItemProprio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProprioActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemProprio);
        jMenuAdmin.add(jSeparator1);

        jMenuItemUsager.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUsager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/People.png"))); // NOI18N
        jMenuItemUsager.setText("Ajouter les usagers");
        jMenuItemUsager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsagerActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemUsager);
        jMenuAdmin.add(jSeparator2);

        jMenuItemApp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.png"))); // NOI18N
        jMenuItemApp.setText("Ajouter les appartements");
        jMenuItemApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAppActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemApp);

        jMenuBar.add(jMenuAdmin);

        jMenuOperation.setText("Opération");

        jMenuItemClient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/smallclient.png"))); // NOI18N
        jMenuItemClient.setText("Ajouter un locataire");
        jMenuItemClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientActionPerformed(evt);
            }
        });
        jMenuOperation.add(jMenuItemClient);
        jMenuOperation.add(jSeparator3);

        jMenuItemClient1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Good mark.png"))); // NOI18N
        jMenuItemClient1.setText("Créer un contrat");
        jMenuItemClient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClient1ActionPerformed(evt);
            }
        });
        jMenuOperation.add(jMenuItemClient1);
        jMenuOperation.add(jSeparator4);

        jMenuItemPaie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPaie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dollar.png"))); // NOI18N
        jMenuItemPaie.setText("Passer un paiement");
        jMenuItemPaie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPaieActionPerformed(evt);
            }
        });
        jMenuOperation.add(jMenuItemPaie);

        jMenuBar.add(jMenuOperation);

        jMenuRapport.setText("Rapport");

        jMenuRepLoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuRepLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/People.png"))); // NOI18N
        jMenuRepLoc.setText("Liste des locataires");
        jMenuRepLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepLocActionPerformed(evt);
            }
        });
        jMenuRapport.add(jMenuRepLoc);
        jMenuRapport.add(jSeparator5);

        jMenuItemRepApp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRepApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.png"))); // NOI18N
        jMenuItemRepApp.setText("Liste des appartements");
        jMenuItemRepApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepAppActionPerformed(evt);
            }
        });
        jMenuRapport.add(jMenuItemRepApp);
        jMenuRapport.add(jSeparator6);

        jMenuItemRepPaie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRepPaie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dollar.png"))); // NOI18N
        jMenuItemRepPaie.setText("Rapport des paiements");
        jMenuItemRepPaie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepPaieActionPerformed(evt);
            }
        });
        jMenuRapport.add(jMenuItemRepPaie);

        jMenuBar.add(jMenuRapport);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsagerActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenUsager().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItemUsagerActionPerformed

    private void jMenuItemAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAppActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new FenAppartement();
                Utilitaire.redimentionnerFrame(frame);       
                frame.setLocationRelativeTo(null);
                frame.setVisible(true); 
            }
        });
    }//GEN-LAST:event_jMenuItemAppActionPerformed

    private void jMenuItemClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenLocataire().setVisible(true);
            }
        });


    }//GEN-LAST:event_jMenuItemClientActionPerformed

    

    private void jMenuItemPaieActionPerformed(java.awt.event.ActionEvent evt) {

        this.setEnabled(true);

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FenPaiement().setVisible(true);

            }
        });
    }

    private void jMenuItemClient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClient1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FenContrat objGui = new FenContrat();
                Utilitaire.redimentionnerFrame(objGui);
                objGui.setLocationRelativeTo(null);
                objGui.setVisible(true);

            }
        });
    }//GEN-LAST:event_jMenuItemClient1ActionPerformed

    private void jMenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitterActionPerformed

    private void jMenuItemProprioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProprioActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenProprio().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItemProprioActionPerformed

    private void jMenuRepLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepLocActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FenClientRapport().setVisible(true);

            }
        });         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRepLocActionPerformed

    private void jMenuItemRepAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepAppActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FenAppRapport().setVisible(true);

            }

        });

    }//GEN-LAST:event_jMenuItemRepAppActionPerformed

    private void jMenuItemRepPaieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepPaieActionPerformed
//appele le fenter de report paiement
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new FenPaiementRapport().setVisible(true);

            }
        }
        );


    }//GEN-LAST:event_jMenuItemRepPaieActionPerformed

    private void ajouterMenuAdmin() {
        listeMenusAdmin.add(jMenuItemProprio);
        listeMenusAdmin.add(jMenuItemUsager);
        listeMenusAdmin.add(jMenuItemApp);
    }

    private ArrayList<JMenuItem> listeMenusAdmin = new ArrayList<JMenuItem>();
    private final String txtTitle = "RESIDENCE DU CALME ";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFicher;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemApp;
    private javax.swing.JMenuItem jMenuItemClient;
    private javax.swing.JMenuItem jMenuItemClient1;
    private javax.swing.JMenuItem jMenuItemPaie;
    private javax.swing.JMenuItem jMenuItemProprio;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JMenuItem jMenuItemRepApp;
    private javax.swing.JMenuItem jMenuItemRepPaie;
    private javax.swing.JMenuItem jMenuItemUsager;
    private javax.swing.JMenu jMenuOperation;
    private javax.swing.JMenu jMenuRapport;
    private javax.swing.JMenuItem jMenuRepLoc;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPanel panelGlobal;
    // End of variables declaration//GEN-END:variables
}
